/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package capture;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class chunk_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public byte xmit_second;
    public byte resource_origin;
    public int resource_id;
    public short chunk_id;
    public byte data[];
 
    public chunk_t()
    {
        data = new byte[58];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x94041c53314332afL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(capture.chunk_t.class))
            return 0L;
 
        classes.add(capture.chunk_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.xmit_second); 
 
        outs.writeByte(this.resource_origin); 
 
        outs.writeInt(this.resource_id); 
 
        outs.writeShort(this.chunk_id); 
 
        outs.write(this.data, 0, 58);
 
    }
 
    public chunk_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public chunk_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static capture.chunk_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        capture.chunk_t o = new capture.chunk_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.xmit_second = ins.readByte();
 
        this.resource_origin = ins.readByte();
 
        this.resource_id = ins.readInt();
 
        this.chunk_id = ins.readShort();
 
        this.data = new byte[(int) 58];
        ins.readFully(this.data, 0, 58); 
    }
 
    public capture.chunk_t copy()
    {
        capture.chunk_t outobj = new capture.chunk_t();
        outobj.utime = this.utime;
 
        outobj.xmit_second = this.xmit_second;
 
        outobj.resource_origin = this.resource_origin;
 
        outobj.resource_id = this.resource_id;
 
        outobj.chunk_id = this.chunk_id;
 
        outobj.data = new byte[(int) 58];
        System.arraycopy(this.data, 0, outobj.data, 0, 58); 
        return outobj;
    }
 
}

