/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package capture;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class perls_mini_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public byte src;
    public byte dest;
    public int user;
 
    public perls_mini_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x0be8c5f7e2d5208fL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(capture.perls_mini_t.class))
            return 0L;
 
        classes.add(capture.perls_mini_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.src); 
 
        outs.writeByte(this.dest); 
 
        outs.writeInt(this.user); 
 
    }
 
    public perls_mini_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public perls_mini_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static capture.perls_mini_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        capture.perls_mini_t o = new capture.perls_mini_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.src = ins.readByte();
 
        this.dest = ins.readByte();
 
        this.user = ins.readInt();
 
    }
 
    public capture.perls_mini_t copy()
    {
        capture.perls_mini_t outobj = new capture.perls_mini_t();
        outobj.utime = this.utime;
 
        outobj.src = this.src;
 
        outobj.dest = this.dest;
 
        outobj.user = this.user;
 
        return outobj;
    }
 
}

