/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package capture;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class perls_jump_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int dest;
    public int next_wypnt;
 
    public perls_jump_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x65bd51cd6882e3f8L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(capture.perls_jump_t.class))
            return 0L;
 
        classes.add(capture.perls_jump_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.dest); 
 
        outs.writeInt(this.next_wypnt); 
 
    }
 
    public perls_jump_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public perls_jump_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static capture.perls_jump_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        capture.perls_jump_t o = new capture.perls_jump_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.dest = ins.readInt();
 
        this.next_wypnt = ins.readInt();
 
    }
 
    public capture.perls_jump_t copy()
    {
        capture.perls_jump_t outobj = new capture.perls_jump_t();
        outobj.utime = this.utime;
 
        outobj.dest = this.dest;
 
        outobj.next_wypnt = this.next_wypnt;
 
        return outobj;
    }
 
}

