/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class april_jserial_JSerial */

#ifndef _Included_april_jserial_JSerial
#define _Included_april_jserial_JSerial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     april_jserial_JSerial
 * Method:    serial_open_jni
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_serial_1open_1jni
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     april_jserial_JSerial
 * Method:    serial_set_baud_jni
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_serial_1set_1baud_1jni
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_jserial_JSerial
 * Method:    serial_set_ctsrts_jni
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_serial_1set_1ctsrts_1jni
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_jserial_JSerial
 * Method:    serial_set_xon_jni
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_serial_1set_1xon_1jni
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_jserial_JSerial
 * Method:    serial_set_mode_jni
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_serial_1set_1mode_1jni
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     april_jserial_JSerial
 * Method:    serial_set_dtr_jni
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_serial_1set_1dtr_1jni
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_jserial_JSerial
 * Method:    serial_set_rts_jni
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_serial_1set_1rts_1jni
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     april_jserial_JSerial
 * Method:    serial_close_jni
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_serial_1close_1jni
  (JNIEnv *, jclass, jint);

/*
 * Class:     april_jserial_JSerial
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_write
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     april_jserial_JSerial
 * Method:    read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_read
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     april_jserial_JSerial
 * Method:    readTimeout
 * Signature: (I[BIII)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_readTimeout
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     april_jserial_JSerial
 * Method:    readTimeoutFully
 * Signature: (I[BIII)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_readTimeoutFully
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     april_jserial_JSerial
 * Method:    readAvailable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_april_jserial_JSerial_readAvailable
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
