/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package hauv;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class bs_imu_t implements lcm.lcm.LCMEncodable
{
    public long time_received;
    public long time;
    public double rate_x;
    public double rate_y;
    public double rate_z;
    public double acc_x;
    public double acc_y;
    public double acc_z;
    public long time_measured;
 
    public bs_imu_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x77249164267d139bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(hauv.bs_imu_t.class))
            return 0L;
 
        classes.add(hauv.bs_imu_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.time_received); 
 
        outs.writeLong(this.time); 
 
        outs.writeDouble(this.rate_x); 
 
        outs.writeDouble(this.rate_y); 
 
        outs.writeDouble(this.rate_z); 
 
        outs.writeDouble(this.acc_x); 
 
        outs.writeDouble(this.acc_y); 
 
        outs.writeDouble(this.acc_z); 
 
        outs.writeLong(this.time_measured); 
 
    }
 
    public bs_imu_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public bs_imu_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hauv.bs_imu_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hauv.bs_imu_t o = new hauv.bs_imu_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.time_received = ins.readLong();
 
        this.time = ins.readLong();
 
        this.rate_x = ins.readDouble();
 
        this.rate_y = ins.readDouble();
 
        this.rate_z = ins.readDouble();
 
        this.acc_x = ins.readDouble();
 
        this.acc_y = ins.readDouble();
 
        this.acc_z = ins.readDouble();
 
        this.time_measured = ins.readLong();
 
    }
 
    public hauv.bs_imu_t copy()
    {
        hauv.bs_imu_t outobj = new hauv.bs_imu_t();
        outobj.time_received = this.time_received;
 
        outobj.time = this.time;
 
        outobj.rate_x = this.rate_x;
 
        outobj.rate_y = this.rate_y;
 
        outobj.rate_z = this.rate_z;
 
        outobj.acc_x = this.acc_x;
 
        outobj.acc_y = this.acc_y;
 
        outobj.acc_z = this.acc_z;
 
        outobj.time_measured = this.time_measured;
 
        return outobj;
    }
 
}

