/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package hauv;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class bs_nvr_t implements lcm.lcm.LCMEncodable
{
    public long time_received;
    public long time;
    public double east_velocity;
    public double north_velocity;
    public double down_velocity;
    public double pitch_rate;
    public double roll_rate;
    public double yaw_rate;
 
    public bs_nvr_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x110ead38a77713b5L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(hauv.bs_nvr_t.class))
            return 0L;
 
        classes.add(hauv.bs_nvr_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.time_received); 
 
        outs.writeLong(this.time); 
 
        outs.writeDouble(this.east_velocity); 
 
        outs.writeDouble(this.north_velocity); 
 
        outs.writeDouble(this.down_velocity); 
 
        outs.writeDouble(this.pitch_rate); 
 
        outs.writeDouble(this.roll_rate); 
 
        outs.writeDouble(this.yaw_rate); 
 
    }
 
    public bs_nvr_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public bs_nvr_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hauv.bs_nvr_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hauv.bs_nvr_t o = new hauv.bs_nvr_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.time_received = ins.readLong();
 
        this.time = ins.readLong();
 
        this.east_velocity = ins.readDouble();
 
        this.north_velocity = ins.readDouble();
 
        this.down_velocity = ins.readDouble();
 
        this.pitch_rate = ins.readDouble();
 
        this.roll_rate = ins.readDouble();
 
        this.yaw_rate = ins.readDouble();
 
    }
 
    public hauv.bs_nvr_t copy()
    {
        hauv.bs_nvr_t outobj = new hauv.bs_nvr_t();
        outobj.time_received = this.time_received;
 
        outobj.time = this.time;
 
        outobj.east_velocity = this.east_velocity;
 
        outobj.north_velocity = this.north_velocity;
 
        outobj.down_velocity = this.down_velocity;
 
        outobj.pitch_rate = this.pitch_rate;
 
        outobj.roll_rate = this.roll_rate;
 
        outobj.yaw_rate = this.yaw_rate;
 
        return outobj;
    }
 
}

