/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package hauv;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class bs_pit_t implements lcm.lcm.LCMEncodable
{
    public long time_received;
    public long time;
    public double pitch_dvl;
    public double pitch_sonar;
 
    public bs_pit_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x4247530f2fc30a13L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(hauv.bs_pit_t.class))
            return 0L;
 
        classes.add(hauv.bs_pit_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.time_received); 
 
        outs.writeLong(this.time); 
 
        outs.writeDouble(this.pitch_dvl); 
 
        outs.writeDouble(this.pitch_sonar); 
 
    }
 
    public bs_pit_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public bs_pit_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hauv.bs_pit_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hauv.bs_pit_t o = new hauv.bs_pit_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.time_received = ins.readLong();
 
        this.time = ins.readLong();
 
        this.pitch_dvl = ins.readDouble();
 
        this.pitch_sonar = ins.readDouble();
 
    }
 
    public hauv.bs_pit_t copy()
    {
        hauv.bs_pit_t outobj = new hauv.bs_pit_t();
        outobj.time_received = this.time_received;
 
        outobj.time = this.time;
 
        outobj.pitch_dvl = this.pitch_dvl;
 
        outobj.pitch_sonar = this.pitch_sonar;
 
        return outobj;
    }
 
}

