/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package hauv;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class bs_rbs_t implements lcm.lcm.LCMEncodable
{
    public long time_received;
    public long time;
    public int battery_number;
    public double voltage;
    public double minimum_cell_voltage;
    public double maximum_cell_voltage;
    public double temperature;
 
    public bs_rbs_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xb4f8e426b4cf54b6L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(hauv.bs_rbs_t.class))
            return 0L;
 
        classes.add(hauv.bs_rbs_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.time_received); 
 
        outs.writeLong(this.time); 
 
        outs.writeInt(this.battery_number); 
 
        outs.writeDouble(this.voltage); 
 
        outs.writeDouble(this.minimum_cell_voltage); 
 
        outs.writeDouble(this.maximum_cell_voltage); 
 
        outs.writeDouble(this.temperature); 
 
    }
 
    public bs_rbs_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public bs_rbs_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hauv.bs_rbs_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hauv.bs_rbs_t o = new hauv.bs_rbs_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.time_received = ins.readLong();
 
        this.time = ins.readLong();
 
        this.battery_number = ins.readInt();
 
        this.voltage = ins.readDouble();
 
        this.minimum_cell_voltage = ins.readDouble();
 
        this.maximum_cell_voltage = ins.readDouble();
 
        this.temperature = ins.readDouble();
 
    }
 
    public hauv.bs_rbs_t copy()
    {
        hauv.bs_rbs_t outobj = new hauv.bs_rbs_t();
        outobj.time_received = this.time_received;
 
        outobj.time = this.time;
 
        outobj.battery_number = this.battery_number;
 
        outobj.voltage = this.voltage;
 
        outobj.minimum_cell_voltage = this.minimum_cell_voltage;
 
        outobj.maximum_cell_voltage = this.maximum_cell_voltage;
 
        outobj.temperature = this.temperature;
 
        return outobj;
    }
 
}

