/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package hauv;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class bs_rcm_t implements lcm.lcm.LCMEncodable
{
    public long time_received;
    public long time;
    public int compass_number;
    public double heading;
    public double pitch;
    public double roll;
    public long time_measured;
 
    public bs_rcm_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x868b0050f05aa4e3L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(hauv.bs_rcm_t.class))
            return 0L;
 
        classes.add(hauv.bs_rcm_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.time_received); 
 
        outs.writeLong(this.time); 
 
        outs.writeInt(this.compass_number); 
 
        outs.writeDouble(this.heading); 
 
        outs.writeDouble(this.pitch); 
 
        outs.writeDouble(this.roll); 
 
        outs.writeLong(this.time_measured); 
 
    }
 
    public bs_rcm_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public bs_rcm_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hauv.bs_rcm_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hauv.bs_rcm_t o = new hauv.bs_rcm_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.time_received = ins.readLong();
 
        this.time = ins.readLong();
 
        this.compass_number = ins.readInt();
 
        this.heading = ins.readDouble();
 
        this.pitch = ins.readDouble();
 
        this.roll = ins.readDouble();
 
        this.time_measured = ins.readLong();
 
    }
 
    public hauv.bs_rcm_t copy()
    {
        hauv.bs_rcm_t outobj = new hauv.bs_rcm_t();
        outobj.time_received = this.time_received;
 
        outobj.time = this.time;
 
        outobj.compass_number = this.compass_number;
 
        outobj.heading = this.heading;
 
        outobj.pitch = this.pitch;
 
        outobj.roll = this.roll;
 
        outobj.time_measured = this.time_measured;
 
        return outobj;
    }
 
}

