/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package hauv;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class pl_san_t implements lcm.lcm.LCMEncodable
{
    public long time;
    public double angle;
 
    public pl_san_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x075d2c4dccb690b3L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(hauv.pl_san_t.class))
            return 0L;
 
        classes.add(hauv.pl_san_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.time); 
 
        outs.writeDouble(this.angle); 
 
    }
 
    public pl_san_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public pl_san_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static hauv.pl_san_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        hauv.pl_san_t o = new hauv.pl_san_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.time = ins.readLong();
 
        this.angle = ins.readDouble();
 
    }
 
    public hauv.pl_san_t copy()
    {
        hauv.pl_san_t outobj = new hauv.pl_san_t();
        outobj.time = this.time;
 
        outobj.angle = this.angle;
 
        return outobj;
    }
 
}

