/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package se;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class add_node_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public short node_type;
    public short sensor_id;
 
    public add_node_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x67240bf57747364eL;
 
    public static final short NODE_POSE2D = (short) 1;
    public static final short NODE_POSE3D = (short) 2;
    public static final short NODE_NOSENSOR = (short) 0;
    public static final short NODE_ODO = (short) 1;
    public static final short NODE_SONAR = (short) 2;
    public static final short NODE_CAMERA = (short) 4;
    public static final short NODE_BATCH = (short) 8;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(se.add_node_t.class))
            return 0L;
 
        classes.add(se.add_node_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeShort(this.node_type); 
 
        outs.writeShort(this.sensor_id); 
 
    }
 
    public add_node_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public add_node_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static se.add_node_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        se.add_node_t o = new se.add_node_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.node_type = ins.readShort();
 
        this.sensor_id = ins.readShort();
 
    }
 
    public se.add_node_t copy()
    {
        se.add_node_t outobj = new se.add_node_t();
        outobj.utime = this.utime;
 
        outobj.node_type = this.node_type;
 
        outobj.sensor_id = this.sensor_id;
 
        return outobj;
    }
 
}

