/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package se;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class goto_t implements lcm.lcm.LCMEncodable
{
    public int mode;
    public long utime_target;
 
    public goto_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xc52c3378aa82e234L;
 
    public static final int MODE_OFF = 0;
    public static final int MODE_GOTO = 1;
    public static final int MODE_RESUME = 2;
    public static final int MODE_GOTO_REL = 3;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(se.goto_t.class))
            return 0L;
 
        classes.add(se.goto_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.mode); 
 
        outs.writeLong(this.utime_target); 
 
    }
 
    public goto_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public goto_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static se.goto_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        se.goto_t o = new se.goto_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.mode = ins.readInt();
 
        this.utime_target = ins.readLong();
 
    }
 
    public se.goto_t copy()
    {
        se.goto_t outobj = new se.goto_t();
        outobj.mode = this.mode;
 
        outobj.utime_target = this.utime_target;
 
        return outobj;
    }
 
}

