/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package se;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class save_waypoint_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int waypoint_id;
 
    public save_waypoint_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3c21f58199511912L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(se.save_waypoint_t.class))
            return 0L;
 
        classes.add(se.save_waypoint_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.waypoint_id); 
 
    }
 
    public save_waypoint_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public save_waypoint_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static se.save_waypoint_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        se.save_waypoint_t o = new se.save_waypoint_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.waypoint_id = ins.readInt();
 
    }
 
    public se.save_waypoint_t copy()
    {
        se.save_waypoint_t outobj = new se.save_waypoint_t();
        outobj.utime = this.utime;
 
        outobj.waypoint_id = this.waypoint_id;
 
        return outobj;
    }
 
}

