/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package vs;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class pallet_list_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int num_pallets;
    public vs.pallet_t pallets[];
 
    public pallet_list_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xd44f51232fab1560L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(vs.pallet_list_t.class))
            return 0L;
 
        classes.add(vs.pallet_list_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + vs.pallet_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.num_pallets); 
 
        for (int a = 0; a < this.num_pallets; a++) {
            this.pallets[a]._encodeRecursive(outs); 
        }
 
    }
 
    public pallet_list_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public pallet_list_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static vs.pallet_list_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        vs.pallet_list_t o = new vs.pallet_list_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.num_pallets = ins.readInt();
 
        this.pallets = new vs.pallet_t[(int) num_pallets];
        for (int a = 0; a < this.num_pallets; a++) {
            this.pallets[a] = vs.pallet_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public vs.pallet_list_t copy()
    {
        vs.pallet_list_t outobj = new vs.pallet_list_t();
        outobj.utime = this.utime;
 
        outobj.num_pallets = this.num_pallets;
 
        outobj.pallets = new vs.pallet_t[(int) num_pallets];
        for (int a = 0; a < this.num_pallets; a++) {
            outobj.pallets[a] = this.pallets[a].copy();
        }
 
        return outobj;
    }
 
}

