#!/bin/bash

SCRIPT=$0
SCRIPT_DIR=$(dirname $SCRIPT)
SCRIPT_NAME=$(basename $SCRIPT)

trap cleanup INT
trap cleanup TERM

function cleanup {    
    echo -e "\n$SCRIPT: Goodbye"
    kill -9 ${tagPid} ${listenPid} ${statePid} &> /dev/null
    exit 0
}

DRONE_STATE_CLASS=team.drone.DroneState

DRONE_TAG_CLASS=team.drone.DroneTag
DRONE_TAG_CONFIG=${SCRIPT_DIR}/../config/droneCam.config

#DRONE_LISTENER_CLASS=team.drone.DroneListenerDR
DRONE_LISTENER_CLASS=team.drone.DroneListener
DRONE_LISTENER_CONFIG=${SCRIPT_DIR}/../config/droneListener.config

cd "$SCRIPT_DIR"

#java lcm.spy.Spy &

java ${DRONE_TAG_CLASS} ${DRONE_TAG_CONFIG} &
tagPid=$!
java ${DRONE_LISTENER_CLASS} ${DRONE_LISTENER_CONFIG} &
listenPid=$!
java ${DRONE_STATE_CLASS} &
statePid=$!

while [ 1 ]; do

    sleep 1

done
