#!/bin/bash

SCRIPTNAME=$(basename $0)
SCRIPTDIR=$(dirname $0)

CLASSPATH=${SCRIPTDIR}/april.jar:${SCRIPTDIR}/lcm.jar

CONFIG_FILE=$SCRIPTDIR/../config/sim.config
LISTENER=team.FastSLAMListener
# LISTENER=april.sim.DummyListener

JAVA='java -ea -server'

${JAVA} april.sim.Simulator -c ${CONFIG_FILE} -l ${LISTENER}
