#!/bin/bash

SCRIPTNAME=$(basename $0)
SCRIPTDIR=$(dirname $0)

CLASSPATH=${SCRIPTDIR}/april.jar:${SCRIPTDIR}/lcm.jar

CONFIG_FILE=$SCRIPTDIR/../config/sim.config
# LISTENER=team.PS3.FastSLAMListener
LISTENER=team.PS2.PartOneListener
# LISTENER=april.sim.DummyListener

JAVA='java -ea -server'
CLASSPATH="${SCRIPTDIR}/april.jar:${SCRIPTDIR}/lcm.jar"

${JAVA} april.sim.Simulator -c ${CONFIG_FILE} -l ${LISTENER}
