#!/bin/bash

SCRIPTNAME=$(basename $0)
SCRIPTDIR=$(dirname $0)

CONFIG_FILE=$SCRIPTDIR/../config/sim.config
LISTENER=team.PartOneListener

JAVA='java -ea -server'

${JAVA} april.sim.Simulator -c ${CONFIG_FILE} -l ${LISTENER}
