(TeX-add-style-hook "finalPaper"
 (lambda ()
    (LaTeX-add-bibliographies
     "IEEEabrv"
     "references")
    (LaTeX-add-labels
     "sec:introduction"
     "sec:systemarchitecture"
     "sec:incrementalsmoothingandmapping"
     "sub:givensrotations"
     "sub:variablereordering"
     "fig:images/reorderResult32Resized"
     "fig:images/reorderResult33Resized"
     "fig:reorder"
     "sub:compoundingoperation"
     "sub:inverseoperation"
     "sub:compositionoperation"
     "sec:apriltags"
     "sec:experiments"
     "sub:simulation"
     "fig:stepTime"
     "sub:quadrotor"
     "sec:conclusion")
    (TeX-run-style-hooks
     "tensor"
     "minted"
     "extarrows"
     "subfigure"
     "epstopdf"
     "comment"
     "amssymb"
     "amsmath"
     "graphicx"
     "parskip"
     "parfill"
     "geometry"
     "latex2e"
     "IEEEtran10"
     "IEEEtran"
     "conference")))

