/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package mrlcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class carmen3d_point_cov_t implements lcm.lcm.LCMEncodable
{
    public double x;
    public double xy;
    public double y;
    public double z;
    public double yaw;
    public double pitch;
    public double roll;
 
    public carmen3d_point_cov_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x5110ab1b98e9e389L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(mrlcm.carmen3d_point_cov_t.class))
            return 0L;
 
        classes.add(mrlcm.carmen3d_point_cov_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeDouble(this.x); 
 
        outs.writeDouble(this.xy); 
 
        outs.writeDouble(this.y); 
 
        outs.writeDouble(this.z); 
 
        outs.writeDouble(this.yaw); 
 
        outs.writeDouble(this.pitch); 
 
        outs.writeDouble(this.roll); 
 
    }
 
    public carmen3d_point_cov_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public carmen3d_point_cov_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static mrlcm.carmen3d_point_cov_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        mrlcm.carmen3d_point_cov_t o = new mrlcm.carmen3d_point_cov_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.x = ins.readDouble();
 
        this.xy = ins.readDouble();
 
        this.y = ins.readDouble();
 
        this.z = ins.readDouble();
 
        this.yaw = ins.readDouble();
 
        this.pitch = ins.readDouble();
 
        this.roll = ins.readDouble();
 
    }
 
    public mrlcm.carmen3d_point_cov_t copy()
    {
        mrlcm.carmen3d_point_cov_t outobj = new mrlcm.carmen3d_point_cov_t();
        outobj.x = this.x;
 
        outobj.xy = this.xy;
 
        outobj.y = this.y;
 
        outobj.z = this.z;
 
        outobj.yaw = this.yaw;
 
        outobj.pitch = this.pitch;
 
        outobj.roll = this.roll;
 
        return outobj;
    }
 
}

