/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package senlcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class acomms_mini_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int src;
    public int dest;
    public int mini_type;
    public int data;
 
    public acomms_mini_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xd8c2b284f1c67dcaL;
 
    public static final int MINI_TYPE_USER = 1;
    public static final int MINI_TYPE_OWTT = 2;
    public static final int MINI_TYPE_ABORT = 3;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(senlcm.acomms_mini_t.class))
            return 0L;
 
        classes.add(senlcm.acomms_mini_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.src); 
 
        outs.writeInt(this.dest); 
 
        outs.writeInt(this.mini_type); 
 
        outs.writeInt(this.data); 
 
    }
 
    public acomms_mini_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public acomms_mini_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static senlcm.acomms_mini_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        senlcm.acomms_mini_t o = new senlcm.acomms_mini_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.src = ins.readInt();
 
        this.dest = ins.readInt();
 
        this.mini_type = ins.readInt();
 
        this.data = ins.readInt();
 
    }
 
    public senlcm.acomms_mini_t copy()
    {
        senlcm.acomms_mini_t outobj = new senlcm.acomms_mini_t();
        outobj.utime = this.utime;
 
        outobj.src = this.src;
 
        outobj.dest = this.dest;
 
        outobj.mini_type = this.mini_type;
 
        outobj.data = this.data;
 
        return outobj;
    }
 
}

