/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package senlcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class acomms_ping_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int src;
    public int dest;
    public double travel_time;
    public double range;
 
    public acomms_ping_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xdffc824ca3571529L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(senlcm.acomms_ping_t.class))
            return 0L;
 
        classes.add(senlcm.acomms_ping_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.src); 
 
        outs.writeInt(this.dest); 
 
        outs.writeDouble(this.travel_time); 
 
        outs.writeDouble(this.range); 
 
    }
 
    public acomms_ping_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public acomms_ping_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static senlcm.acomms_ping_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        senlcm.acomms_ping_t o = new senlcm.acomms_ping_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.src = ins.readInt();
 
        this.dest = ins.readInt();
 
        this.travel_time = ins.readDouble();
 
        this.range = ins.readDouble();
 
    }
 
    public senlcm.acomms_ping_t copy()
    {
        senlcm.acomms_ping_t outobj = new senlcm.acomms_ping_t();
        outobj.utime = this.utime;
 
        outobj.src = this.src;
 
        outobj.dest = this.dest;
 
        outobj.travel_time = this.travel_time;
 
        outobj.range = this.range;
 
        return outobj;
    }
 
}

