/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package senlcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class acomms_owtt_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int src;
    public int dest;
    public double owtt;
    public double range;
    public int receiver_clk_mode;
    public int sender_clk_mode;
 
    public acomms_owtt_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x64810b5033e3e28bL;
 
    public static final int CLK_MODE_NO_SYNC_TO_PPS_AND_CCCLK_BAD = 0;
    public static final int CLK_MODE_NO_SYNC_TO_PPS_AND_CCCLK_GOOD = 1;
    public static final int CLK_MODE_SYNC_TO_PPS_AND_CCCLK_BAD = 2;
    public static final int CLK_MODE_SYNC_TO_PPS_AND_CCCLK_GOOD = 3;
    public static final int CLK_MODE_UNKNOWN = 4;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(senlcm.acomms_owtt_t.class))
            return 0L;
 
        classes.add(senlcm.acomms_owtt_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.src); 
 
        outs.writeInt(this.dest); 
 
        outs.writeDouble(this.owtt); 
 
        outs.writeDouble(this.range); 
 
        outs.writeInt(this.receiver_clk_mode); 
 
        outs.writeInt(this.sender_clk_mode); 
 
    }
 
    public acomms_owtt_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public acomms_owtt_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static senlcm.acomms_owtt_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        senlcm.acomms_owtt_t o = new senlcm.acomms_owtt_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.src = ins.readInt();
 
        this.dest = ins.readInt();
 
        this.owtt = ins.readDouble();
 
        this.range = ins.readDouble();
 
        this.receiver_clk_mode = ins.readInt();
 
        this.sender_clk_mode = ins.readInt();
 
    }
 
    public senlcm.acomms_owtt_t copy()
    {
        senlcm.acomms_owtt_t outobj = new senlcm.acomms_owtt_t();
        outobj.utime = this.utime;
 
        outobj.src = this.src;
 
        outobj.dest = this.dest;
 
        outobj.owtt = this.owtt;
 
        outobj.range = this.range;
 
        outobj.receiver_clk_mode = this.receiver_clk_mode;
 
        outobj.sender_clk_mode = this.sender_clk_mode;
 
        return outobj;
    }
 
}

