/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package senlcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class dstar_ssp1_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public double p_abs;
    public double p_gage;
    public double p_atm;
    public double depth;
    public double temperature;
 
    public dstar_ssp1_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x241e05ab010741cbL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(senlcm.dstar_ssp1_t.class))
            return 0L;
 
        classes.add(senlcm.dstar_ssp1_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeDouble(this.p_abs); 
 
        outs.writeDouble(this.p_gage); 
 
        outs.writeDouble(this.p_atm); 
 
        outs.writeDouble(this.depth); 
 
        outs.writeDouble(this.temperature); 
 
    }
 
    public dstar_ssp1_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public dstar_ssp1_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static senlcm.dstar_ssp1_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        senlcm.dstar_ssp1_t o = new senlcm.dstar_ssp1_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.p_abs = ins.readDouble();
 
        this.p_gage = ins.readDouble();
 
        this.p_atm = ins.readDouble();
 
        this.depth = ins.readDouble();
 
        this.temperature = ins.readDouble();
 
    }
 
    public senlcm.dstar_ssp1_t copy()
    {
        senlcm.dstar_ssp1_t outobj = new senlcm.dstar_ssp1_t();
        outobj.utime = this.utime;
 
        outobj.p_abs = this.p_abs;
 
        outobj.p_gage = this.p_gage;
 
        outobj.p_atm = this.p_atm;
 
        outobj.depth = this.depth;
 
        outobj.temperature = this.temperature;
 
        return outobj;
    }
 
}

