/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package senlcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class kvh_dsp3000_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public byte mode;
    public double data;
 
    public kvh_dsp3000_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x912a628047321ba5L;
 
    public static final byte RATE_MODE = (byte) 1;
    public static final byte DELTA_MODE = (byte) 2;
    public static final byte ANGLE_MODE = (byte) 3;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(senlcm.kvh_dsp3000_t.class))
            return 0L;
 
        classes.add(senlcm.kvh_dsp3000_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.mode); 
 
        outs.writeDouble(this.data); 
 
    }
 
    public kvh_dsp3000_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public kvh_dsp3000_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static senlcm.kvh_dsp3000_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        senlcm.kvh_dsp3000_t o = new senlcm.kvh_dsp3000_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.mode = ins.readByte();
 
        this.data = ins.readDouble();
 
    }
 
    public senlcm.kvh_dsp3000_t copy()
    {
        senlcm.kvh_dsp3000_t outobj = new senlcm.kvh_dsp3000_t();
        outobj.utime = this.utime;
 
        outobj.mode = this.mode;
 
        outobj.data = this.data;
 
        return outobj;
    }
 
}

