/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package senlcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class relay_t implements lcm.lcm.LCMEncodable
{
    public String label;
    public String group;
    public boolean state;
    public boolean exclude_all;
 
    public relay_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xda84521184f3fc57L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(senlcm.relay_t.class))
            return 0L;
 
        classes.add(senlcm.relay_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        __strbuf = new char[this.label.length()]; this.label.getChars(0, this.label.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.group.length()]; this.group.getChars(0, this.group.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeByte( this.state ? 1 : 0); 
 
        outs.writeByte( this.exclude_all ? 1 : 0); 
 
    }
 
    public relay_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public relay_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static senlcm.relay_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        senlcm.relay_t o = new senlcm.relay_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.label = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.group = new String(__strbuf);
 
        this.state = ins.readByte()!=0;
 
        this.exclude_all = ins.readByte()!=0;
 
    }
 
    public senlcm.relay_t copy()
    {
        senlcm.relay_t outobj = new senlcm.relay_t();
        outobj.label = this.label;
 
        outobj.group = this.group;
 
        outobj.state = this.state;
 
        outobj.exclude_all = this.exclude_all;
 
        return outobj;
    }
 
}

