/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package senlcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class tritech_es_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public double range;
 
    public tritech_es_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x5535163fa13b78beL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(senlcm.tritech_es_t.class))
            return 0L;
 
        classes.add(senlcm.tritech_es_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeDouble(this.range); 
 
    }
 
    public tritech_es_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public tritech_es_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static senlcm.tritech_es_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        senlcm.tritech_es_t o = new senlcm.tritech_es_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.range = ins.readDouble();
 
    }
 
    public senlcm.tritech_es_t copy()
    {
        senlcm.tritech_es_t outobj = new senlcm.tritech_es_t();
        outobj.utime = this.utime;
 
        outobj.range = this.range;
 
        return outobj;
    }
 
}

