/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package perllcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class ardrone_drive_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public float vx;
    public float vy;
    public float vz;
    public float vr;
 
    public ardrone_drive_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xb816e9423d0683c1L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(perllcm.ardrone_drive_t.class))
            return 0L;
 
        classes.add(perllcm.ardrone_drive_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeFloat(this.vx); 
 
        outs.writeFloat(this.vy); 
 
        outs.writeFloat(this.vz); 
 
        outs.writeFloat(this.vr); 
 
    }
 
    public ardrone_drive_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public ardrone_drive_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static perllcm.ardrone_drive_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        perllcm.ardrone_drive_t o = new perllcm.ardrone_drive_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.vx = ins.readFloat();
 
        this.vy = ins.readFloat();
 
        this.vz = ins.readFloat();
 
        this.vr = ins.readFloat();
 
    }
 
    public perllcm.ardrone_drive_t copy()
    {
        perllcm.ardrone_drive_t outobj = new perllcm.ardrone_drive_t();
        outobj.utime = this.utime;
 
        outobj.vx = this.vx;
 
        outobj.vy = this.vy;
 
        outobj.vz = this.vz;
 
        outobj.vr = this.vr;
 
        return outobj;
    }
 
}

