/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package perllcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class est_navigator_debug_pred_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public double dt;
 
    public est_navigator_debug_pred_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x447369c4330d1364L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(perllcm.est_navigator_debug_pred_t.class))
            return 0L;
 
        classes.add(perllcm.est_navigator_debug_pred_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeDouble(this.dt); 
 
    }
 
    public est_navigator_debug_pred_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public est_navigator_debug_pred_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static perllcm.est_navigator_debug_pred_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        perllcm.est_navigator_debug_pred_t o = new perllcm.est_navigator_debug_pred_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.dt = ins.readDouble();
 
    }
 
    public perllcm.est_navigator_debug_pred_t copy()
    {
        perllcm.est_navigator_debug_pred_t outobj = new perllcm.est_navigator_debug_pred_t();
        outobj.utime = this.utime;
 
        outobj.dt = this.dt;
 
        return outobj;
    }
 
}

