/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package perllcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class lb3_timestamp_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public long wtime;
    public long mytime;
    public long frame;
 
    public lb3_timestamp_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x17533568ee2f5334L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(perllcm.lb3_timestamp_t.class))
            return 0L;
 
        classes.add(perllcm.lb3_timestamp_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeLong(this.wtime); 
 
        outs.writeLong(this.mytime); 
 
        outs.writeLong(this.frame); 
 
    }
 
    public lb3_timestamp_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public lb3_timestamp_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static perllcm.lb3_timestamp_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        perllcm.lb3_timestamp_t o = new perllcm.lb3_timestamp_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.wtime = ins.readLong();
 
        this.mytime = ins.readLong();
 
        this.frame = ins.readLong();
 
    }
 
    public perllcm.lb3_timestamp_t copy()
    {
        perllcm.lb3_timestamp_t outobj = new perllcm.lb3_timestamp_t();
        outobj.utime = this.utime;
 
        outobj.wtime = this.wtime;
 
        outobj.mytime = this.mytime;
 
        outobj.frame = this.frame;
 
        return outobj;
    }
 
}

