/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package perllcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class van_verify_ack_t implements lcm.lcm.LCMEncodable
{
    public long utime1;
    public long utime2;
    public boolean valid;
    public boolean stop_verifying;
 
    public van_verify_ack_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x19c7a7698198e530L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(perllcm.van_verify_ack_t.class))
            return 0L;
 
        classes.add(perllcm.van_verify_ack_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime1); 
 
        outs.writeLong(this.utime2); 
 
        outs.writeByte( this.valid ? 1 : 0); 
 
        outs.writeByte( this.stop_verifying ? 1 : 0); 
 
    }
 
    public van_verify_ack_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public van_verify_ack_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static perllcm.van_verify_ack_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        perllcm.van_verify_ack_t o = new perllcm.van_verify_ack_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime1 = ins.readLong();
 
        this.utime2 = ins.readLong();
 
        this.valid = ins.readByte()!=0;
 
        this.stop_verifying = ins.readByte()!=0;
 
    }
 
    public perllcm.van_verify_ack_t copy()
    {
        perllcm.van_verify_ack_t outobj = new perllcm.van_verify_ack_t();
        outobj.utime1 = this.utime1;
 
        outobj.utime2 = this.utime2;
 
        outobj.valid = this.valid;
 
        outobj.stop_verifying = this.stop_verifying;
 
        return outobj;
    }
 
}

