/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package perllcm;
 
import java.io.*;
import java.nio.*;
import java.util.*;
import lcm.lcm.*;
 
public final class van_feature_collection_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public String channel;
    public int ntypes;
    public perllcm.van_feature_t f[];
    public perllcm.van_calib_t calib;
    public perllcm.van_scene_prior_t scene_prior;
 
    public van_feature_collection_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xd9a00ad9f34e6a10L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class>());
    }
 
    public static long _hashRecursive(ArrayList<Class> classes)
    {
        if (classes.contains(perllcm.van_feature_collection_t.class))
            return 0L;
 
        classes.add(perllcm.van_feature_collection_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + perllcm.van_feature_t._hashRecursive(classes)
             + perllcm.van_calib_t._hashRecursive(classes)
             + perllcm.van_scene_prior_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        __strbuf = new char[this.channel.length()]; this.channel.getChars(0, this.channel.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.ntypes); 
 
        for (int a = 0; a < this.ntypes; a++) {
            this.f[a]._encodeRecursive(outs); 
        }
 
        this.calib._encodeRecursive(outs); 
 
        this.scene_prior._encodeRecursive(outs); 
 
    }
 
    public van_feature_collection_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public van_feature_collection_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static perllcm.van_feature_collection_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        perllcm.van_feature_collection_t o = new perllcm.van_feature_collection_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.channel = new String(__strbuf);
 
        this.ntypes = ins.readInt();
 
        this.f = new perllcm.van_feature_t[(int) ntypes];
        for (int a = 0; a < this.ntypes; a++) {
            this.f[a] = perllcm.van_feature_t._decodeRecursiveFactory(ins);
        }
 
        this.calib = perllcm.van_calib_t._decodeRecursiveFactory(ins);
 
        this.scene_prior = perllcm.van_scene_prior_t._decodeRecursiveFactory(ins);
 
    }
 
    public perllcm.van_feature_collection_t copy()
    {
        perllcm.van_feature_collection_t outobj = new perllcm.van_feature_collection_t();
        outobj.utime = this.utime;
 
        outobj.channel = this.channel;
 
        outobj.ntypes = this.ntypes;
 
        outobj.f = new perllcm.van_feature_t[(int) ntypes];
        for (int a = 0; a < this.ntypes; a++) {
            outobj.f[a] = this.f[a].copy();
        }
 
        outobj.calib = this.calib.copy();
 
        outobj.scene_prior = this.scene_prior.copy();
 
        return outobj;
    }
 
}

